[pytest]
pythonpath = .
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short

markers = 
    smoke: fast basic tests
    sanity: main functions works
    regreesion: all tests
    login: just login functions
    ui: UI testing
    slow: slow tests
    wip: work-in-progreess